[project]
name = "visitor-badge"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10, <3.13"
dependencies = [
    "anybadge>=1.16.0",
    "fastapi[standard]>=0.115.12",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.39",
    "uvicorn>=0.34.0",
]
